language: node_js
version: "~> 1.0.0"
cache: yarn
jobs:
  include:
  - stage: test
    script: yarn test-single && codecov
  - stage: npm-bundle
    script: yarn build && npm version $TRAVIS_BRANCH --allow-same-version --allow-empty
    deploy:
      edge: true
      provider: npm
      email: bameyrick@gmail.com
      api_token:
        secure: loOM0Pn033Ip9cpvcp2PIAEUZE6x85vUbV4XjesTzlnxyiI2DgfEjK9xC9grkoEDqSyW/nAWv5kSzzIAq2m2oSUlhtL0GnkrisqTCLcveREAVpTEucOWrW6qIuTAB2rvYXY1auv1YMyJvXNC50XD3LalO4Omy0pfodFQL3Nz6MvLgiUyhOCOyTay/9tp5+qfumkJOXdcKKL/sWA5LawK3xSFk5TLw6ePjC5DvMoKpAuVEhSuCQ8lVHX9QOOI5f7IV7ECW3Prh9NuPK4hpkkSw0TWZ3J0OyXKEcux5dM7I+K6TeHfip3fwIUnz9kU7aPuX5mn9xWoWvwdM/jT4+akTy2aygW+CRfIpaS8mpAj60+gj8+M6J2bvV/AN1tmodQ2nTRD5nUSzo93o6qlsGbeA3Enn94kbZ0w815ddaoWJWt+lbe4bRaTrAYDKtEH48H+9AYRj5XQmUnirbRdca4SstLiJ7pX61+SoQMDDOCeDBk2rokkVuHn3QGUWRnRaOYn3jezpKLpTTTgJQ632SiA1Ld2Y6GVj++Z79nwvHExpKk0ir13Vo04WukfaknWAx8t8+m2x2sQnZxId6eM9vdJEX277Qw4Qj6BQRQi5wnxe757tKosbENMbsJQD3y98zK+q4b2umxlPDuLHqRfJJZk6+5X8KBthrYn6ApnSdmScHg=
      on:
        tags: true
stages:
- name: test
  if: tag IS NOT present
- name: npm-bundle
  if: tag IS present
